#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare utorrent for snap
#
# Date: Feb 14 2018
#

dlut () {
    wget --accept "*.exe" --content-disposition --trust-server-names http://download-hr.utorrent.com/track/stable/endpoint/utorrent/os/windows &> /dev/null
    for fnts in andalemo.ttf arialbd.ttf arialbi.ttf ariali.ttf arial.ttf ariblk.ttf comicbd.ttf comic.ttf courbd.ttf courbi.ttf couri.ttf cour.ttf georgiab.ttf georgiai.ttf georgia.ttf georgiaz.ttf impact.ttf l_10646.ttf lucon.ttf micross.ttf symbol.ttf tahomabd.ttf tahoma.ttf timesbd.ttf timesbi.ttf timesi.ttf times.ttf trebucbd.ttf trebucbi.ttf trebucit.ttf trebuc.ttf verdanab.ttf verdanai.ttf verdana.ttf verdanaz.ttf webdings.ttf wingding.ttf
    do
    wget https://github.com/caarlos0-graveyard/msfonts/blob/master/fonts/$fnts?raw=true -P share/wine/fonts &> /dev/null
    mv share/wine/fonts/$fnts?raw=true share/wine/fonts/$fnts
    done
}

mkut () {
    7z x uTorrent.exe Carrier.exe -o"usr/share/utorrent"
    mv usr/share/utorrent/Carrier.exe usr/share/utorrent/utorrent.exe
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    wrestool -x -t3 -n62 -R usr/share/utorrent/utorrent.exe > usr/share/pixmaps/utorrent.png
}

mkdsk () {
ver="$(wget http://www.utorrent.com/downloads/win -q -S -O - 2>&1 | grep Stable | awk '{print $2}' | sed 's|Stable(||')"
bnum="$(wget http://www.utorrent.com/downloads/win -q -S -O - 2>&1 | grep Stable | awk '{print $4}' | sed 's|)||')"
cat > utorrent.desktop <<'EOF1'
[Desktop Entry]
Name=utorrent
GenericName=BitTorrent Client
Comment=The world's most popular BitTorrent client
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/utorrent.png
Exec=utorrent %U
StartupWMClass=utorrent.exe
Categories=Network;FileTransfer;P2P;
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
EOF1
sed -i -e 's|Version=|Version='"$ver.$bnum"'|g' utorrent.desktop
}

dlut
mkut
mkdsk
mv utorrent bin && mv utorrent.desktop usr/share/applications
rm uTorrent.exe dl_ut