#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   notepad3 wrapper for snap
#
# Date: Feb 14 2018
#

ARCH="i386-linux-gnu"

export WINEVERPATH=$SNAP
export PATH=$SNAP/bin:$SNAP/usr:bin:$PATH 
export WINESERVER=$SNAP/bin/wineserver
export WINELOADER=$SNAP/bin/wine
export WINEDLLPATH=$SNAP/lib/wine/fakedlls
export WINEPREFIX=$SNAP_USER_COMMON/.wine
export WINEDLLOVERRIDES="mscoree,mshtml="
# export WINEDEBUG=-all
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib:$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH"

export HOME=$SNAP_USER_COMMON
export XDG_DATA_HOME=$SNAP_USER_COMMON/usr/share

# utorrent env
progName=utorrent
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe

if [ ! -d $progHome ];then
mkdir -p $progHome
touch $progHome/settings.dat
fi

# Delete broken symlinks
find -L "$progHome" -type l -delete &> /dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &> /dev/null

# Add torrent(s)/magnet link(s)
for i; do # for i = for i in "$@"
    # Add path in Wine form (e.g. "z:/home/user/Desktop/lol.torrent")
    if [[ -f /${i#?:} ]]; then 
        torrents+=("z:${i#?:}")   # When opened through .desktop or Wine path (e.g. z:/*)
    elif [[ $i != magnet:* ]]; then
        torrents+=("z:$(pwd)/$i") # When path only partial or in current directory
    else    # Magnet links
        torrents+=("$i")
    fi
done

if [ -z "$1" ] ; then
  wine "$progHome/$progBin"
else
  wine start /unix "$progHome/$progBin" "${torrents[@]}"
fi
